# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
  docker-pull-ec-2:
    needs: build

    runs-on: ubuntu-latest
    steps:
    - name: Creating SSH Configuration File
      env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deployment.pem
          chmod 600 ~/.ssh/deployment.pem
          cat >> ~/.ssh/config <<END
          Host deploy_ec2
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deployment.pem
            StrictHostKeyChecking no
            END

    - name: Deploy to EC2
      run: |
          ssh deploy_ec2 "mkdir -p ml_process_demo_iris"
          ssh deploy_ec2 "mkdir temp"
          ssh deploy_ec2 "git clone https://github.com/farrelarrizal/ml_process_demo_iris.git temp"
          ssh deploy_ec2 "rsync -a ./temp ./ml_process_demo"
          ssh deploy_ec2 "rm -rf temp/"
          ssh deploy_ec2 "cd ml_process_demo_iris"
          ssh deploy_ec2 "cd ml_process_demo_iris && sudo docker compose down"
          ssh deploy_ec2 "cd ml_process_demo_iris || sudo docker rmi iris-classifier-api -f || sudo docker rmi iris-classifier-streamlit -f"
          ssh deploy_ec2 "cd ml_process_demo_iris && sudo docker-compose up -d"
